services:
  app:
    build: .
    ports:
      - "8989:8989"
    depends_on:
      - db
    env_file:
      - path: ./.env
        required: true
  db:
    image: "postgres:16"
    env_file:
      - path: ./.env
        required: true  
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
volumes:
  postgres: